name: Build

on: [workflow_dispatch]

jobs:
  build:
    name: Gradle-distZip
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2
      # Set up JAVA
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      # Build
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build